version: "2"

services:
  httpd:
    image: httpd:2.4-alpine
    ports:
      - 80:80
    volumes_from:
      - fpm
    links:
      - fpm
    volumes:
      - ./docker/apache/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro
      - ./docker/apache/vhosts:/usr/local/apache2/conf/vhosts:ro

  fpm:
    image: stanislasp/laravel-5-php-7.3:latest
    expose:
      - 9000
    ports:
      - 9000:9000
    volumes:
      - .:/var/www/html:rw
    links:
      - mysql
      - redis
      - mailcatcher

  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql/conf:/etc/mysql/conf.d/custom.cnf:ro
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: stanislaspoisson
      MYSQL_USER: stanislaspoisson
      MYSQL_PASSWORD: stanislaspoisson

  redis:
    image: redis:5-alpine
    command: redis-server --appendonly yes
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

  mailcatcher:
    image: jeanberu/mailcatcher:0.6.5
    ports:
      - 1025:1025
      - 1080:1080

volumes:
  db_data:
    driver: local
  redis_data:
    driver: local
